<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platform>x86</Platform>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cosmos.System2.v2" Version="2025.*" />
    <PackageReference Include="Cosmos.Debug.Kernel.v2" Version="2025.*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="LowLevel.asm" />
  </ItemGroup>

</Project>
