name: Build Plus OS

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Build Binary (Native AOT)
      # Мы явно создаем папку и просим положить туда результат
      run: |
        mkdir -p ./output
        dotnet publish PlusOS.csproj -c Release -r linux-x64 --self-contained true /p:PublishAot=true -o ./output

    - name: List files (для отладки)
      # Эта команда покажет в логах, как именно называется твой файл
      run: ls -R ./output

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PlusOS-Binary
        # Берем ВСЁ содержимое папки output
        path: ./output/*
