name: Build Plus OS

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x # Обновили до 8-ки

    - name: Restore dependencies
      # Теперь он увидит nuget.config и найдет Cosmos
      run: dotnet restore PlusOS.csproj

    - name: Build Project
      run: dotnet build PlusOS.csproj --configuration Release
